(() => {
  const canvas = document.querySelector('#game-canvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  const scoreEl = document.querySelector('#score');
  const highScoreEl = document.querySelector('#high-score');
  const statusEl = document.querySelector('#game-status');
  const startButton = document.querySelector('#start-game');
  const pauseButton = document.querySelector('#pause-game');
  const restartButton = document.querySelector('#restart-game');
  const wallMode = document.querySelector('#wall-mode');
  const speedMode = document.querySelector('#speed-mode');
  const difficultyMode = document.querySelector('#difficulty-mode');
  const cell = 20;
  const columns = canvas.width / cell;
  const rows = canvas.height / cell;
  const speeds = { slow: 190, normal: 135, fast: 90 };
  const directions = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } };
  let snake = [], food = { x: 10, y: 10 }, enemies = [], direction = directions.right, queuedDirection = direction;
  let timer = null, running = false, paused = false, score = 0, highScore = Number(localStorage.getItem('kd-high-score') || 0);
  highScoreEl.textContent = String(highScore);

  const same = (a, b) => a.x === b.x && a.y === b.y;
  const randomCell = () => ({ x: Math.floor(Math.random() * columns), y: Math.floor(Math.random() * rows) });
  const occupied = (point) => snake.some((part) => same(part, point)) || enemies.some((enemy) => same(enemy, point));
  const freeCell = () => { let point = randomCell(); let attempts = 0; while (occupied(point) && attempts < 100) { point = randomCell(); attempts += 1; } return point; };
  const setStatus = (message) => { statusEl.textContent = message; };
  const updateScore = () => { scoreEl.textContent = String(score); highScoreEl.textContent = String(highScore); };
  const drawCell = (point, color, radius = 3) => { const x = point.x * cell + 2; const y = point.y * cell + 2; ctx.fillStyle = color; ctx.beginPath(); ctx.roundRect(x, y, cell - 4, cell - 4, radius); ctx.fill(); };
  const draw = () => { ctx.fillStyle = '#070b13'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(113,217,255,.05)'; for (let x = 0; x <= columns; x += 1) { ctx.beginPath(); ctx.moveTo(x * cell, 0); ctx.lineTo(x * cell, canvas.height); ctx.stroke(); } for (let y = 0; y <= rows; y += 1) { ctx.beginPath(); ctx.moveTo(0, y * cell); ctx.lineTo(canvas.width, y * cell); ctx.stroke(); } drawCell(food, '#71d9ff', 8); enemies.forEach((enemy) => drawCell(enemy, '#ff6f91', 7)); snake.forEach((part, index) => drawCell(part, index === 0 ? '#f2f5f8' : '#71d9ff', 6)); };
  const reset = () => { snake = [{ x: 8, y: 10 }, { x: 7, y: 10 }, { x: 6, y: 10 }]; direction = directions.right; queuedDirection = direction; score = 0; enemies = []; for (let i = 0; i < 4; i += 1) enemies.push(freeCell()); food = freeCell(); updateScore(); draw(); };
  const setDirection = (next) => { const candidate = directions[next]; if (!candidate || (candidate.x + direction.x === 0 && candidate.y + direction.y === 0)) return; queuedDirection = candidate; };
  const moveEnemy = (enemy) => { const choices = Object.values(directions).filter((candidate) => candidate.x !== -enemy.dx || candidate.y !== -enemy.dy); if (Math.random() < .35 || !enemy.dx) { const candidate = choices[Math.floor(Math.random() * choices.length)]; enemy.dx = candidate.x; enemy.dy = candidate.y; } const next = { x: enemy.x + enemy.dx, y: enemy.y + enemy.dy }; if (next.x < 0 || next.x >= columns || next.y < 0 || next.y >= rows || snake.some((part) => same(part, next))) { enemy.dx = -enemy.dx || 1; enemy.dy = -enemy.dy; return; } enemy.x = next.x; enemy.y = next.y; };
  const endGame = () => { running = false; paused = false; if (timer) { clearInterval(timer); timer = null; } startButton.disabled = false; pauseButton.disabled = true; setStatus('게임 오버 · 재시작 가능'); };
  const tick = () => { if (paused) return; direction = queuedDirection; let head = { x: snake[0].x + direction.x, y: snake[0].y + direction.y }; if (wallMode.value === 'wrap') { head = { x: (head.x + columns) % columns, y: (head.y + rows) % rows }; } else if (head.x < 0 || head.x >= columns || head.y < 0 || head.y >= rows) return endGame(); if (snake.some((part) => same(part, head)) || enemies.some((enemy) => same(enemy, head))) return endGame(); snake.unshift(head); if (same(head, food)) { score += 10; if (score > highScore) { highScore = score; localStorage.setItem('kd-high-score', String(highScore)); } food = freeCell(); } else snake.pop(); enemies.forEach(moveEnemy); if (enemies.some((enemy) => same(enemy, snake[0]))) return endGame(); if (difficultyMode.checked && score > 0 && score % 50 === 0) { clearInterval(timer); timer = setInterval(tick, Math.max(55, speeds[speedMode.value] - score)); } updateScore(); draw(); };
  const start = () => { if (running && paused) { paused = false; setStatus('플레이 중'); return; } if (running) return; reset(); running = true; paused = false; startButton.disabled = true; pauseButton.disabled = false; setStatus('플레이 중'); if (timer) clearInterval(timer); timer = setInterval(tick, speeds[speedMode.value]); };
  startButton.addEventListener('click', start); pauseButton.addEventListener('click', () => { if (!running) return; paused = !paused; pauseButton.textContent = paused ? '계속하기' : '일시정지'; setStatus(paused ? '일시정지' : '플레이 중'); }); restartButton.addEventListener('click', () => { if (timer) clearInterval(timer); timer = null; running = false; pauseButton.textContent = '일시정지'; reset(); setStatus('시작을 눌러 플레이'); startButton.disabled = false; pauseButton.disabled = true; });
  document.addEventListener('keydown', (event) => { const keys = { ArrowUp: 'up', w: 'up', W: 'up', ArrowDown: 'down', s: 'down', S: 'down', ArrowLeft: 'left', a: 'left', A: 'left', ArrowRight: 'right', d: 'right', D: 'right' }; if (keys[event.key]) { event.preventDefault(); setDirection(keys[event.key]); } });
  document.querySelectorAll('[data-direction]').forEach((button) => button.addEventListener('pointerdown', () => setDirection(button.dataset.direction)));
  reset();
})();
