(() => {
  const year = document.querySelector('#current-year');
  if (year) year.textContent = String(new Date().getFullYear());
  document.body.classList.add('is-ready');
  const root = document.documentElement;
  const themeButton = document.querySelector('#theme-toggle');
  const decreaseButton = document.querySelector('#font-decrease');
  const resetButton = document.querySelector('#font-reset');
  const increaseButton = document.querySelector('#font-increase');
  const motionButton = document.querySelector('#motion-toggle');
  const status = document.querySelector('#accessibility-status');
  const storage = (key, value) => { try { if (value === undefined) return localStorage.getItem(key); localStorage.setItem(key, value); } catch (_) { return null; } };
  const setStatus = (message) => { if (status) status.textContent = message; };
  const setTheme = (theme) => { root.dataset.theme = theme; themeButton?.setAttribute('aria-pressed', String(theme === 'light')); if (themeButton) themeButton.textContent = theme === 'light' ? '다크 모드' : '라이트 모드'; storage('kd-theme', theme); setStatus(theme === 'light' ? '라이트 모드 적용' : '다크 모드 적용'); };
  const setScale = (scale) => { root.style.setProperty('--font-scale', String(scale)); storage('kd-font-scale', String(scale)); setStatus(`글자 크기 ${Math.round(scale * 100)}% 적용`); };
  const setMotion = (reduced) => { root.classList.toggle('reduce-motion', reduced); motionButton?.setAttribute('aria-pressed', String(reduced)); if (motionButton) motionButton.textContent = reduced ? '애니메이션 켜기' : '애니메이션 감소'; storage('kd-reduce-motion', String(reduced)); setStatus(reduced ? '애니메이션 감소 적용' : '애니메이션 기본 설정'); };
  setTheme(storage('kd-theme') || 'dark'); setScale(Number(storage('kd-font-scale')) || 1); setMotion(storage('kd-reduce-motion') === 'true');
  themeButton?.addEventListener('click', () => setTheme(root.dataset.theme === 'light' ? 'dark' : 'light'));
  decreaseButton?.addEventListener('click', () => setScale(Math.max(.9, (Number(root.style.getPropertyValue('--font-scale')) || 1) - .1)));
  resetButton?.addEventListener('click', () => setScale(1));
  increaseButton?.addEventListener('click', () => setScale(Math.min(1.2, (Number(root.style.getPropertyValue('--font-scale')) || 1) + .1)));
  motionButton?.addEventListener('click', () => setMotion(!root.classList.contains('reduce-motion')));
})();
