(() => {
  const canvas = document.querySelector('#tetris-canvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  const scoreEl = document.querySelector('#tetris-score');
  const highScoreEl = document.querySelector('#tetris-high-score');
  const statusEl = document.querySelector('#tetris-status');
  const startButton = document.querySelector('#tetris-start');
  const pauseButton = document.querySelector('#tetris-pause');
  const restartButton = document.querySelector('#tetris-restart');
  const cols = 10, rows = 20, cell = 20;
  const colors = ['#71d9ff', '#f5d76e', '#c39bff', '#75e0a1', '#ff829d', '#7ea6ff', '#ffad70'];
  const shapes = [[[1, 1, 1, 1]], [[1, 1], [1, 1]], [[0, 1, 0], [1, 1, 1]], [[0, 1, 1], [1, 1, 0]], [[1, 1, 0], [0, 1, 1]], [[1, 0, 0], [1, 1, 1]], [[0, 0, 1], [1, 1, 1]]];
  let board = [], current = null, x = 0, y = 0, score = 0, highScore = Number(localStorage.getItem('kd-tetris-high-score') || 0), timer = null, running = false, paused = false;
  highScoreEl.textContent = String(highScore);
  const setStatus = (message) => { statusEl.textContent = message; };
  const emptyBoard = () => Array.from({ length: rows }, () => Array(cols).fill(0));
  const clone = (shape) => shape.map((row) => row.slice());
  const updateScore = () => { scoreEl.textContent = String(score); highScoreEl.textContent = String(highScore); };
  const drawCell = (cx, cy, color) => { ctx.fillStyle = color; ctx.fillRect(cx * cell + 1, cy * cell + 1, cell - 2, cell - 2); };
  const draw = () => { ctx.fillStyle = '#070b13'; ctx.fillRect(0, 0, canvas.width, canvas.height); board.forEach((row, rowIndex) => row.forEach((value, colIndex) => { if (value) drawCell(colIndex, rowIndex, colors[value - 1]); })); if (current) current.forEach((row, rowIndex) => row.forEach((value, colIndex) => { if (value) drawCell(x + colIndex, y + rowIndex, colors[value - 1]); })); };
  const collides = (shape, offsetX, offsetY) => shape.some((row, rowIndex) => row.some((value, colIndex) => value && (offsetX + colIndex < 0 || offsetX + colIndex >= cols || offsetY + rowIndex >= rows || (offsetY + rowIndex >= 0 && board[offsetY + rowIndex][offsetX + colIndex]))));
  const rotate = (shape) => shape[0].map((_, colIndex) => shape.map((row) => row[colIndex]).reverse());
  const spawn = () => { const index = Math.floor(Math.random() * shapes.length); current = clone(shapes[index]).map((row) => row.map((value) => value ? index + 1 : 0)); x = Math.floor((cols - current[0].length) / 2); y = 0; if (collides(current, x, y)) endGame(); };
  const merge = () => current.forEach((row, rowIndex) => row.forEach((value, colIndex) => { if (value && y + rowIndex >= 0) board[y + rowIndex][x + colIndex] = value; }));
  const clearLines = () => { let cleared = 0; board = board.filter((row) => { if (row.every(Boolean)) { cleared += 1; return false; } return true; }); while (board.length < rows) board.unshift(Array(cols).fill(0)); if (cleared) { score += [0, 100, 300, 500, 800][cleared]; if (score > highScore) { highScore = score; localStorage.setItem('kd-tetris-high-score', String(highScore)); } updateScore(); } };
  const lock = () => { merge(); clearLines(); spawn(); };
  const tick = () => { if (paused || !running) return; if (!collides(current, x, y + 1)) y += 1; else lock(); draw(); };
  const move = (dx) => { if (!running || paused || !current) return; if (!collides(current, x + dx, y)) x += dx; draw(); };
  const turn = () => { if (!running || paused || !current) return; const rotated = rotate(current); if (!collides(rotated, x, y)) current = rotated; draw(); };
  const drop = () => { if (!running || paused || !current) return; while (!collides(current, x, y + 1)) y += 1; lock(); draw(); };
  const endGame = () => { running = false; paused = false; if (timer) { clearInterval(timer); timer = null; } startButton.disabled = false; pauseButton.disabled = true; setStatus('게임 오버 · 재시작 가능'); draw(); };
  const reset = () => { board = emptyBoard(); current = null; x = 0; y = 0; score = 0; updateScore(); spawn(); draw(); };
  const start = () => { if (running && paused) { paused = false; setStatus('플레이 중'); return; } if (running) return; reset(); running = true; paused = false; startButton.disabled = true; pauseButton.disabled = false; setStatus('플레이 중'); if (timer) clearInterval(timer); timer = setInterval(tick, 500); };
  startButton.addEventListener('click', start); pauseButton.addEventListener('click', () => { if (!running) return; paused = !paused; pauseButton.textContent = paused ? '계속하기' : '일시정지'; setStatus(paused ? '일시정지' : '플레이 중'); }); restartButton.addEventListener('click', () => { if (timer) clearInterval(timer); timer = null; running = false; pauseButton.textContent = '일시정지'; reset(); setStatus('시작을 눌러 플레이'); startButton.disabled = false; pauseButton.disabled = true; });
  document.addEventListener('keydown', (event) => { if (!running && event.key === 'Enter') return start(); const actions = { ArrowLeft: () => move(-1), a: () => move(-1), A: () => move(-1), ArrowRight: () => move(1), d: () => move(1), D: () => move(1), ArrowUp: turn, w: turn, W: turn, ArrowDown: tick, s: tick, S: tick, ' ': drop }; if (actions[event.key]) { event.preventDefault(); actions[event.key](); } });
  document.querySelectorAll('[data-tetris-action]').forEach((button) => button.addEventListener('pointerdown', () => ({ left: () => move(-1), right: () => move(1), down: tick, rotate: turn }[button.dataset.tetrisAction]())));
  reset();
})();
